### ISSUE TITLE
关于非640*640尺寸输入

### ISSUE THREAD

**Issue by jieyangzhang** [hanson-young/nniefacelib#10]
您好：
        有个问题咨询一下，如果我想使用1080p尺寸的图片源作为输入，应该采取什么分辨率呢？
        我有尝试过将原图resize到640*640得到的结果效果不好。
        我的想法是将原图从1920×1080缩放为1138×640；查阅资料发现全卷积是可以输入任意尺寸大小的输入，我的想法是在结果获取中找到每640*640在1138*640中的x轴偏移量来得到框坐标在原图的偏移量。想问一下这种解决思路会不会存在问题？
        没有什么深度学习基础，可能问的问题比较低浅，期待您的回答谢谢～

**Comment by jieyangzhang** [comment]
关于原图缩放到640*640效果不好的原因，我感觉是因为人脸变形了。。。

**Comment by hanson-young** [comment]
最好不要让人脸变形，可以加padding或者重新量化成你想要的尺寸

**Comment by jieyangzhang** [comment]
加padding是什么意思，将1080p的图像缩放到310*640，然后补充空余部分到640*640吗？

**Comment by hanson-young** [comment]
对，是的
