### ISSUE TITLE
makefile.debug

### ISSUE THREAD

**Issue by ChenShisen** [hanson-young/nniefacelib#11]
想在nnie_face_api.c 中加opencv代码，想在图片上框出人脸，makefile.debug可以怎么改呢，小白改了好久，opencv头文件找不到，把.c改成.cpp可以吗，迷糊了一天，谢谢大佬

**Comment by hanson-young** [comment]
可以封装成C api，用C++调用

**Comment by ChenShisen** [comment]
as32ReaultDet 这个地方存储了检测结果，调用接口时怎么获取这个结果呢，哪个接口有返回吗

**Comment by hanson-young** [comment]
没有提供返回结果  创建个数组buffer传参就行
