### ISSUE TITLE
PFPD-dataset

### ISSUE THREAD

**Issue by xuguozhi** [hanson-young/nniefacelib#18]
你好，感谢提供了PFPLD-Dataset.rar的数据集！下载后准备用来训练，但发现train_data/list.txt 中landmark部分有许多-256.0的点，请问这是否是正常的结果？是不是因为300W中是68点，故意补充-256.0作为虚点 便于训练的？ 
PS：众多的.txt文件 用哪个来训练？

**Comment by hanson-young** [comment]
是的  有些值是缺失的，用list.txt就好

**Comment by xuguozhi** [comment]
哈哈，感谢，正在训练，请问现在的robust model 训到了loss到多少？

**Comment by xuguozhi** [comment]
还有疑问，这些-256.0的点会对正常点训练造成影响吗？

**Comment by hanson-young** [comment]
不好意思，看到了，忘记回复  
Epoch: 0, val pose MAE:7.5796, val lds NME:29.0318, val lds ION:4.8545, lr:0.001000

**Comment by hanson-young** [comment]
> 还有疑问，这些-256.0的点会对正常点训练造成影响吗？

那些值不参与计算

**Comment by xuguozhi** [comment]
明白了，数据集里有标志表明哪些参与计算的吧

**Comment by hanson-young** [comment]
主要靠type_flag进行控制

**Comment by xuguozhi** [comment]
再一次感谢！
