### ISSUE TITLE
wk量化支持膨胀卷积吗

### ISSUE THREAD

**Issue by mahxn0** [hanson-young/nniefacelib#21]
膜拜大佬,交流一下:下图是我的网络输入
![image](https://user-images.githubusercontent.com/19154155/80438609-27133c00-8937-11ea-8514-c4064c4e139c.png)

输入后紧跟的是膨胀卷积,量化的时候不报错,但是这层的量化差异非常大, 大佬有遇到过这个问题吗

**Comment by hanson-young** [comment]
我没用到过dilated conv，你可以尝试吧dilated conv后面的层都去了然后进行调试
