### ISSUE TITLE
请问作者研究过不同的人脸检测器制作数据集而不是用groud truth ，对于精度有没有影响

### ISSUE THREAD

**Issue by budaLi** [hanson-young/nniefacelib#22]
你说的是PFPLD吗？

**Comment by budaLi** [comment]
> 你说的是PFPLD吗？
是的  我看到你制作的数据集都是按关键点去裁剪人脸的

**Comment by hanson-young** [comment]
crop有做随机处理，其实还好，直接用检测的去做也是可以的，不过即便是检测，还是得做随机处理。因为目的并不是单一的去适配一种检测器，很可能在应用的时候回归的框做了square

**Comment by budaLi** [comment]
![image](https://user-images.githubusercontent.com/31475416/80581699-1995a900-8a40-11ea-823f-0425ff769394.png)
其实还是比较依赖人脸检测器的， 如果训练和测试用的是不一样的人脸框，效果应该会有出入的

**Comment by hanson-young** [comment]
级联系统，前面一级不能太差
