### ISSUE TITLE
请教下关于这个makefile的问题

### ISSUE THREAD

**Issue by imhere113** [hanson-young/nniefacelib#23]
你好，最近打算往3516dv300上移植一套人脸检测的算法哈哈，看了下大佬这makefile，小弟有个疑问想请教。
include $(PWD)/../Makefile.param

include $(PWD)/../../$(ARM_ARCH)_$(OSTYPE).mak

这两个makefile是在海思提供的开发环境里吗？ 因为您这的路径里没有。。

**Comment by imhere113** [comment]
我理解应该是 hisi提供的sample里会有 不知道是否是这样，因为实际板子还没买，不太清楚哈哈，还在做调研

**Comment by hanson-young** [comment]
SDK版本的问题
