### ISSUE TITLE
The forward speed of wk model

### ISSUE THREAD

**Issue by amsturdy** [hanson-young/nniefacelib#3]
Hi, why the forward speed of wk model is slower than yours, (maybe caused by the different version of nnie mapper tool ?)

Is there any difference beween CPU mapper and GPU mapper? all wk models gennerated by these work on nnie?

**Comment by hanson-young** [comment]
`void NNIE_FACE_DETECTOR_INIT(char *pcModelName, float threshold, int isLog);`
please set isLog = 0
Printing information is time consuming，you can check inference stage and post processing respectively

**Comment by peyer** [comment]
@hanson-young Thanks for your share ! The latency of mobileFaceNet running on single NNIE Core I test is ~14ms, if use two NNIE Core, shall it became ~7ms?
