### ISSUE TITLE
关键点抖动问题

### ISSUE THREAD

**Issue by hejing-maker** [hanson-young/nniefacelib#30]
运行PFPLD和之前的PFLD代码，发现作者代码的关键点抖动移动端mobilenet0.25模型明显改善，想问下，这个改善主要和什么有关，如何解决关键点抖动问题？

**Comment by hanson-young** [comment]
loss有关，我做过对比，虽然强调attribute的想法听上去很完美，但是实际效果并不会很好

**Comment by hejing-maker** [comment]
只是通过loss改善的吗，我感觉你的这个改善主要还是数据集够多，算了好几个loss，不知道大佬有什么建议呢



---原始邮件---
发件人: "hanson.young"<notifications@github.com&gt;
发送时间: 2020年5月19日(周二) 下午4:25
收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送: "hejing-maker"<776248249@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)




 
loss有关，我做过对比，虽然强调attribute的想法听上去很完美，但是实际效果并不会很好

**Comment by hanson-young** [comment]
加额外数据的话是对眼睛部位进行了加强，并且让姿态回归的更好，即便不加其他数据，关键点也能比原版的会好一些



---原始邮件---
发件人: "hejing-maker"<notifications@github.com&gt;
发送时间: 2020年5月19日(周二) 晚上6:23
收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hanson.young"<1139143281@qq.com&gt;;
主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)




 只是通过loss改善的吗，我感觉你的这个改善主要还是数据集够多，算了好几个loss，不知道大佬有什么建议呢 
 
 
 
 ---原始邮件--- 
 发件人: "hanson.young"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月19日(周二) 下午4:25 
 收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&amp;gt;; 
 抄送: "hejing-maker"<776248249@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30) 
 
 
 
 
   
 loss有关，我做过对比，虽然强调attribute的想法听上去很完美，但是实际效果并不会很好

**Comment by hejing-maker** [comment]
你这个数据集中是只用了300wlp中没翻转的图片还是说两个都用到了，我看只是用了没翻转的那一部分，为什么不加翻转的数据集，这样不是数据更多了吗



---原始邮件---
发件人: "hanson.young"<notifications@github.com&gt;
发送时间: 2020年5月19日(周二) 晚上6:37
收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送: "hejing-maker"<776248249@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)




 加额外数据的话是对眼睛部位进行了加强，并且让姿态回归的更好，即便不加其他数据，关键点也能比原版的会好一些 
 
 
 
 ---原始邮件--- 
 发件人: "hejing-maker"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月19日(周二) 晚上6:23 
 收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&amp;gt;; 
 抄送: "Comment"<comment@noreply.github.com&amp;gt;;"hanson.young"<1139143281@qq.com&amp;gt;; 
 主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30) 
 
 
 
 
  只是通过loss改善的吗，我感觉你的这个改善主要还是数据集够多，算了好几个loss，不知道大佬有什么建议呢  
   
   
   
  ---原始邮件---  
  发件人: "hanson.young"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年5月19日(周二) 下午4:25  
  收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&amp;amp;gt;;  
  抄送: "hejing-maker"<776248249@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题: Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)  
   
   
   
   
     
  loss有关，我做过对比，虽然强调attribute的想法听上去很完美，但是实际效果并不会很好

**Comment by hanson-young** [comment]
其实300wlp已经完成了翻转操作，所以就不需要再做一次了。我主要是加了random eraser让遮挡下的性能更好

**Comment by hejing-maker** [comment]
这个几个翻转的你没有在txt中添加？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hanson.young"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午2:32
收件人:&nbsp;"hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送:&nbsp;"776248249"<776248249@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)





 
其实300wlp已经完成了翻转操作，所以就不需要再做一次了。我主要是加了random eraser让遮挡下的性能更好

**Comment by hejing-maker** [comment]
&nbsp;还有一个问题：你的LFPW数据集在训练的时候有68关键点的坐标信息，参与训练，为什么测试集中LFPW所有的关键点坐标都变为-256,加上测试数据关键点信息不是更好？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hanson.young"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午2:32
收件人:&nbsp;"hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送:&nbsp;"776248249"<776248249@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hanson-young/nniefacelib] 关键点抖动问题 (#30)





 
其实300wlp已经完成了翻转操作，所以就不需要再做一次了。我主要是加了random eraser让遮挡下的性能更好

**Comment by hanson-young** [comment]
你说的是AFLW2000吧，那个数据集貌似只有21个点，一般论文里是用这个数据集来评估角度的呢
