### ISSUE TITLE
在3516dv300上试了试retinaface，nnie耗时34ms，cpu耗时比较夸张有1s多。

### ISSUE THREAD

**Issue by imhere113** [hanson-young/nniefacelib#35]
在3516dv300上试了试retinaface，nnie耗时34ms，cpu耗时比较夸张有1s多，是不是nms耗时比较严重？

**Comment by hanson-young** [comment]
请把打印的log关了  
https://github.com/hanson-young/nniefacelib/issues/3

**Comment by imhere113** [comment]
嗯，printf是阻塞函数，我猜可能stdout缓冲引起的高耗时。 去掉打印就不几乎不耗时了

**Comment by imhere113** [comment]
再请教一个问题哈~~ 现在输入是bgr，我能使用yuv420吗？，我看代码里fillsrcdata的时候有420这个分支

**Comment by hanson-young** [comment]
可以，但需要自己重新转模型



---原始邮件---
发件人: "imhere113"<notifications@github.com&gt;
发送时间: 2020年6月17日(周三) 中午11:29
收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hanson.young"<1139143281@qq.com&gt;;
主题: Re: [hanson-young/nniefacelib] 在3516dv300上试了试retinaface，nnie耗时34ms，cpu耗时比较夸张有1s多。 (#35)




 
再请教一个问题哈~~ 现在输入是bgr，我能使用yuv420吗？，我看代码里fillsrcdata的时候有420这个分支
