### ISSUE TITLE
关于PFPLD0.25

### ISSUE THREAD

**Issue by zengwbz** [hanson-young/nniefacelib#36]
请问你的PFPLD训练精度怎么样？
我用PFPLD-0.25训练200Epoch到这个程度很难收敛了：
Epoch: 200, train pose loss: 0.2786, train lds loss:17.5812, val pose MAE:8.4492, val lds NME:29.3052, val lds ION:5.0024, lr:0.000010
不知道这够不够。

**Comment by hanson-young** [comment]
关键点部分已经OK了，比我用0.25训练的结果还好一些，pose稍微差一点，处于7.5-8.0

**Comment by zengwbz** [comment]
> 关键点部分已经OK了，比我用0.25训练的结果还好一些，pose稍微差一点，处于7.5-8.0

好的，非常感谢，我主要是想用来做pose检测，请问有什么办法来提高pose精度吗？

**Comment by hanson-young** [comment]
你可以试试不要去做关键点的训练

**Comment by zys1994** [comment]
你们说的pfld-0.25指的是通道做了0.25吗？ 像下面
```
newchannels = int(64*0.25)
newchannels2 = newchannels*2
```

**Comment by hanson-young** [comment]
对
