### ISSUE TITLE
老哥,我把你这mnet算法移植到了我的板子上，结果坐标有些疑问

### ISSUE THREAD

**Issue by imhere113** [hanson-young/nniefacelib#37]
我是实时从vpss里取的640*640的图像，送到mnet算法里后，发现出来的结果的坐标，有时候是负数，请问是做过坐标转换了吗？还是您的坐标系不是左上角是原点？

**Comment by imhere113** [comment]
我可视化了一下，，发现这种情况是我只有下半张脸，，，哈哈

**Comment by hanson-young** [comment]
左上角为原点
