### ISSUE TITLE
请教关于batch并行计算即retinaface输入尺寸的问题

### ISSUE THREAD

**Issue by jstzwjr** [hanson-young/nniefacelib#44]
您好！想请教两个问题
1、请问nnie是否支持batch并行计算，是否有相关例程；
2、您提供的retinaface代码是否支持输入宽、高不相等的情况，我把输入改成宽高不等的情况，输出会多很多不准确的框，而且有的坐标值为负几百。
感谢

**Comment by hanson-young** [comment]
1、支持，但是速度是线性增加的，约等于没有
2、支持
