### ISSUE TITLE
关于视频流测试

### ISSUE THREAD

**Issue by xc724655471** [hanson-young/nniefacelib#45]
请问你接入过海思视频流进行过测试吗？我用图片测试人脸识别没有问题，但接入海思vpss处理后的视频流无法检测到人脸。

**Comment by hanson-young** [comment]
数据格式的问题吧，修改sample里面那个加载图像的借口

**Comment by xc724655471** [comment]
> 数据格式的问题吧，修改sample里面那个加载图像的接口

修改量化配置文件里面的image_type解决了。确实是数据格式问题。
