### ISSUE TITLE
数据集说明

### ISSUE THREAD

**Issue by zchuang11** [hanson-young/nniefacelib#5]
你好，麻烦提供一下数据集文件的说明，里面文件很多

**Comment by hanson-young** [comment]
训练直接使用test_data和train_data就行，其他的不用管，如果你想自己生成训练数据的话，请参考PRNet（https://github.com/YadiraF/PRNet）和PFLD（https://github.com/polarisZhao/PFLD-pytorch）

**Comment by budaLi** [comment]
您好 请问300wlp中有标注的人脸框没有 我看到那个roi data不太像
