### ISSUE TITLE
pfld 结果不正确

### ISSUE THREAD

**Issue by merria28** [hanson-young/nniefacelib#50]
你好，我用你的caffemodel生成了一个wk文件，在海思芯片上运行之后发现得到的landmark结果不对；我输入的是一个cvMat图像，通过channel，height，width的遍历顺序对输入Blob赋值的，指针是HI_8U，输出从blob拿出后直接除了4096，然后乘了112，我的人脸图像就是112的

不知道哪里不正确。。。

还不能贴图，崩溃了

**Comment by hanson-young** [comment]
你可以在海思上也保存逐层的inference数据，然后去和pc上仿真的对比下，查一下在什么地方出了问题
