### ISSUE TITLE
onnx转化caffe模型出错，ONNX node of type Pad is not supported.

### ISSUE THREAD

**Issue by guojilei** [hanson-young/nniefacelib#51]
按照作者的思路，把作者的那个、models/pretrained/checkpoint_robust.pth,利用convert_to_onnx.py转化为onnx,模型，可以成功得到一个onnx模型，但是在把此onnx模型利用convertCaffe.py，转化为caffe模型时候出错。爆出ONNX node of type Pad is not supported.。我的torch版本为1.3.0+cpu,我的onnx版本为1.6.0，请问什么情况，有遇到过吗 ？该如何解决

**Comment by hanson-young** [comment]
这个指令你用了吗？python3 -m onnxsim ./models/onnx/checkpoint_epoch_final.onnx ./models/onnx/pfpld.onnx

**Comment by guojilei** [comment]
没有，这个指令是在什么使用？谢谢

**Comment by guojilei** [comment]
你好 我看到你说需要用那个 python3 -m onnxsim ./models/onnx/checkpoint_epoch_final.onnx ./models/onnx/pfpld.onnx指令了，麻烦问一下我不是太明白，这个指令是怎么使用的 还有就是这个指令是做什么用的
