### ISSUE TITLE
Hi3559 可以运行作者的retinaface代码，亲测可以

### ISSUE THREAD

**Issue by northeastsquare** [hanson-young/nniefacelib#53]
简单记录一下，后面谁可能用到
1. 类型转换，作者代码里面使用类似用一个函数做了类型转换，要模仿Hi3559里面使用c语言里面，类型强制转换
2. 模型要使用作者提供baidupan里面下载的模型和cfg文件等，使用Hi3559配套的ruyi工具重新生成
![det41](https://user-images.githubusercontent.com/3086078/91625897-8b293800-e9dd-11ea-90e3-6b419f69509d.jpg)

x : 226.078995 y: 322.559723 w:269.671021 h384.721527
result rect: 0, 133.953354, 246.735474, 194.546646, 338.514526
result lds: 1, 170.500000, 282.062500
result lds: 2, 177.187500, 278.781250
result lds: 3, 192.875000, 289.546875
result lds: 4, 183.093750, 313.906250
result lds: 5, 187.171875, 311.953125
result rect: 1, 457.710876, 84.530075, 523.195374, 173.344925
result lds: 1, 468.250000, 121.718750
result lds: 2, 481.625000, 119.015625
result lds: 3, 467.750000, 139.484375
result lds: 4, 481.578125, 153.562500
result lds: 5, 490.937500, 150.656250
result rect: 2, 226.078995, 322.559723, 269.671021, 384.721527
result lds: 1, 255.812500, 346.234375
result lds: 2, 260.234375, 343.093750
result lds: 3, 269.750000, 354.765625
result lds: 4, 260.031250, 369.000000
result lds: 5, 263.406250, 366.937500

**Comment by pangxiaowen** [comment]
您好，能发我一份您转化好的hi3559的retinaface模型吗？我这边转化后模型的输出结果一直不正确。

**Comment by northeastsquare** [comment]
https://github.com/hanson-young/nniefacelib/tree/master/data/nnie_model/face 这里就有
