### ISSUE TITLE
nnie 均值、scale, 打印各层特征。使用image_list；使用cfg文件，与nnie生成wk文件的cfg一样，不需要修改。

### ISSUE THREAD

**Issue by northeastsquare** [hanson-young/nniefacelib#54]
解决了作者提到的CNN_convert_bin_and_print_featuremap.py里面的bug
https://gist.github.com/northeastsquare/bb44c1e14e3f3cbcbe9c0df18ca1bb12

**Comment by hanson-young** [comment]
感谢 @northeastsquare
