### ISSUE TITLE
SAMPLE_SVP_NNIE_CONVERT_64BIT_ADDR

### ISSUE THREAD

**Issue by pangxiaowen** [hanson-young/nniefacelib#55]
您好。我目前在做hi3559的开发工作，准备尝试移植您的lib库，我想问一下SAMPLE_SVP_NNIE_CONVERT_64BIT_ADDR这个函数的实现方式，3559的sdk中并没有同名函数。十分感谢

**Comment by hanson-young** [comment]
最好是在hi3559的sample上移植核心的那部分代码，确实有些不同的地方

**Comment by The-OldWang** [comment]
> 您好。我目前在做hi3559的开发工作，准备尝试移植您的lib库，我想问一下SAMPLE_SVP_NNIE_CONVERT_64BIT_ADDR这个函数的实现方式，3559的sdk中并没有同名函数。十分感谢

你可以通过强制类型转换来解决这个问题。
