### ISSUE TITLE
请问您可以将data/nnie_model/face/下的caffe模型和转为海思模型对应的prototxt也上传一下吗？

### ISSUE THREAD

**Issue by The-OldWang** [hanson-young/nniefacelib#56]
十分感谢作者的工作。请问您可以将data/nnie_model/face/下的caffe模型和转为海思模型对应的prototxt也上传一下吗？我想修改一下输入数据类型为yuv。
谢谢！

**Comment by hanson-young** [comment]
https://github.com/honghuCode/mobileFacenet-ncnn/tree/feature/mobilefacenet-mxnet2caffe

**Comment by hanson-young** [comment]
@The-OldWang https://github.com/honghuCode/mobileFacenet-ncnn/tree/feature/mobilefacenet-mxnet2caffe

**Comment by The-OldWang** [comment]
> @The-OldWang https://github.com/honghuCode/mobileFacenet-ncnn/tree/feature/mobilefacenet-mxnet2caffe
好的，非常感谢你的回复。
