### ISSUE TITLE
关于pose的问题

### ISSUE THREAD

**Issue by MrHwc** [hanson-young/nniefacelib#67]
作者，你好。你在README里说使用PRNet重新标注了角度，请问你是使用的[官方模型](https://github.com/YadiraF/PRNet)还是自己重新训练的？你使用的模型角度准确吗？和那些商用的API对比，官方PRNet模型还是有些差异。

**Comment by hanson-young** [comment]
PRNet其实不是很准，特别是抬头情况下，效果不理想，后来就没用了，选择融合了300WLP直接训练，效果就好多了，后面训练的角度效果我认为是OK的

**Comment by MrHwc** [comment]
谢谢解答，我发现HopeNet、img2pose的角度也可以，作者如果感兴趣可以尝试下。
