### ISSUE TITLE
为什么对于lds个数为68的数据，训练时只是使用部分点的数据呢。

### ISSUE THREAD

**Issue by BinZheng1-pp** [hanson-young/nniefacelib#76]
https://github.com/hanson-young/nniefacelib/blob/d014ffe1868656c0c19866ba79d4d5ca97a4301a/PFPLD/pfld/loss.py#L58

**Comment by hanson-young** [comment]
因为并不是每个点的标注都和106个点的一致，或许你看起来比较像，但实际训练出来是有差异的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hanson-young/nniefacelib] 为什么对于lds个数为68的数据，训练时只是使用部分点的数据呢。 (Issue #76)




 
https://github.com/hanson-young/nniefacelib/blob/d014ffe1868656c0c19866ba79d4d5ca97a4301a/PFPLD/pfld/loss.py#L58

**Comment by BinZheng1-pp** [comment]
验证了下的确是这样，多谢
