### ISSUE TITLE
nniefacelib/vision/nnie_face_api.c的第347行代码逻辑咨询

### ISSUE THREAD

**Issue by jieyangzhang** [hanson-young/nniefacelib#8]
大佬您好，咨询一下nniefacelib/vision/nnie_face_api.c的第347行：
c_pt = (c + anchor_num) * cls_h * cls_w;
为什么是(c + anchor_num)呢，不是应该是2吗？
我理解应该是for (c = 0; c < 2; ++c)
{
c_pt = c * anchor_num * cls_h * cls_w;

这样。。。可以请教一下您的代码逻辑是什么意思吗？

**Comment by hanson-young** [comment]
举个栗子


name:score_stride32_output0_4_20_20
stride: 80
blob type :0
{
&nbsp; &nbsp; &nbsp; &nbsp; c :4
&nbsp; &nbsp; &nbsp; &nbsp; h :20
&nbsp; &nbsp; &nbsp; &nbsp; w :20&nbsp;
}

这个是一个得分的输出层，写代码写的有点早了，不过意思就是，这4个通道中，只有anchor_num个通道是有效数据，具体是那两个可以在量化的时候看到，你也可以打印出来看，代码我是根据我之前写的ncnn版本来微改的，也可以参考那个



---原始邮件---
发件人: "jieyangzhang"<notifications@github.com&gt;
发送时间: 2020年3月30日(周一) 晚上6:54
收件人: "hanson-young/nniefacelib"<nniefacelib@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hanson-young/nniefacelib] nniefacelib/vision/nnie_face_api.c的第347行代码逻辑咨询 (#8)




 
大佬您好，咨询一下nniefacelib/vision/nnie_face_api.c的第347行：
 c_pt = (c + anchor_num) * cls_h * cls_w;
 为什么是(c + anchor_num)呢，不是应该是2吗？
 我理解应该是for (c = 0; c < 2; ++c)
 {
 c_pt = c * anchor_num * cls_h * cls_w;
 
这样。。。可以请教一下您的代码逻辑是什么意思吗？

**Comment by jieyangzhang** [comment]
好的，明白了。谢谢解答～
